### ISSUE TITLE
Unauthorized (HTTP 401) in Horizon Dashboard from nova client

### ISSUE THREAD

**Issue by jowolf** [jowolf/openstack-standalone-formula#5]
root@openstack14:/usr/share/openstack-dashboard# ./manage.py runserver 0:8000 --insecure
Validating models...

0 errors found
September 07, 2014 - 23:47:30
Django version 1.6.1, using settings 'openstack_dashboard.settings'
Starting development server at http://0:8000/
Quit the server with CONTROL-C.

REQ: curl -i 'http://0.0.0.0:8774/v2/5d74bac5f4654fc09fb64fe4bb168bc8/extensions' -X GET -H "X-Auth-Project-Id: 5d74bac5f4654fc09fb64fe4bb168bc8" -H "User-Agent: python-novaclient" -H "Accept: application/json" -H "X-Auth-Token: 6ea2e1318631cd2b2e07265b5f8b8062"

New session created for: (http://0.0.0.0:8774)
INFO:urllib3.connectionpool:Starting new HTTP connection (1): 0.0.0.0
DEBUG:urllib3.connectionpool:Setting read timeout to None
DEBUG:urllib3.connectionpool:"GET /v2/5d74bac5f4654fc09fb64fe4bb168bc8/extensions HTTP/1.1" 401 23
RESP: [401] CaseInsensitiveDict({'date': 'Sun, 07 Sep 2014 23:47:39 GMT', 'content-length': '23', 'content-type': 'text/plain', 'www-authenticate': "Keystone uri='https://127.0.0.1:35357'"})
RESP BODY: Authentication required

REQ: curl -i 'http://0.0.0.0:8774/v2/5d74bac5f4654fc09fb64fe4bb168bc8' -X GET -H "X-Auth-Project-Id: 5d74bac5f4654fc09fb64fe4bb168bc8" -H "X-Auth-Key: 6ea2e1318631cd2b2e07265b5f8b8062" -H "Accept: application/json" -H "X-Auth-User: admin" -H "User-Agent: python-novaclient"

DEBUG:urllib3.connectionpool:Setting read timeout to None
DEBUG:urllib3.connectionpool:"GET /v2/5d74bac5f4654fc09fb64fe4bb168bc8 HTTP/1.1" 401 23
RESP: [401] CaseInsensitiveDict({'date': 'Sun, 07 Sep 2014 23:47:39 GMT', 'content-length': '23', 'content-type': 'text/plain', 'www-authenticate': "Keystone uri='https://127.0.0.1:35357'"})
RESP BODY: Authentication required

Internal Server Error: /admin/
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, _callback_args, *_callback_kwargs)
  File "/usr/lib/python2.7/dist-packages/horizon/decorators.py", line 38, in dec
    return view_func(request, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/horizon/decorators.py", line 86, in dec
    return view_func(request, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/horizon/decorators.py", line 54, in dec
    return view_func(request, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/horizon/decorators.py", line 38, in dec
    return view_func(request, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/horizon/decorators.py", line 86, in dec
    return view_func(request, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, _args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/horizon/tables/views.py", line 154, in get
    handled = self.construct_tables()
  File "/usr/lib/python2.7/dist-packages/horizon/tables/views.py", line 145, in construct_tables
    handled = self.handle_table(table)
  File "/usr/lib/python2.7/dist-packages/horizon/tables/views.py", line 118, in handle_table
    data = self._get_data_dict()
  File "/usr/lib/python2.7/dist-packages/horizon/tables/views.py", line 181, in _get_data_dict
    self._data = {self.table_class._meta.name: self.get_data()}
  File "/usr/share/openstack-dashboard/openstack_dashboard/dashboards/admin/overview/views.py", line 60, in get_data
    data = super(GlobalOverview, self).get_data()
  File "/usr/share/openstack-dashboard/openstack_dashboard/usage/views.py", line 43, in get_data
    self.usage.summarize(_self.usage.get_date_range())
  File "/usr/share/openstack-dashboard/openstack_dashboard/usage/base.py", line 200, in summarize
    if not api.nova.extension_supported('SimpleTenantUsage', self.request):
  File "/usr/lib/python2.7/dist-packages/horizon/utils/memoized.py", line 90, in wrapped
    value = cache[key] = func(_args, *_kwargs)
  File "/usr/share/openstack-dashboard/openstack_dashboard/api/nova.py", line 752, in extension_supported
    extensions = list_extensions(request)
  File "/usr/lib/python2.7/dist-packages/horizon/utils/memoized.py", line 90, in wrapped
    value = cache[key] = func(_args, *_kwargs)
  File "/usr/share/openstack-dashboard/openstack_dashboard/api/nova.py", line 743, in list_extensions
    return nova_list_extensions.ListExtManager(novaclient(request)).show_all()
  File "/usr/lib/python2.7/dist-packages/novaclient/v1_1/contrib/list_extensions.py", line 37, in show_all
    return self._list("/extensions", 'extensions')
  File "/usr/lib/python2.7/dist-packages/novaclient/base.py", line 64, in _list
    _resp, body = self.api.client.get(url)
  File "/usr/lib/python2.7/dist-packages/novaclient/client.py", line 283, in get
    return self._cs_request(url, 'GET', *_kwargs)
  File "/usr/lib/python2.7/dist-packages/novaclient/client.py", line 275, in _cs_request
    raise e
Unauthorized: Unauthorized (HTTP 401)
[07/Sep/2014 23:47:39] "GET /admin/ HTTP/1.1" 500 245023

joe@openstack14:~$

**Comment by jowolf** [comment]
user-roles needed to be set up correctly, along with users, endpoints, services, and roles, but this wasn't the ultimate solution.

After debug-level logging of horizon, nova, and keystone, ultimately, due to misconfiguration as a result of salt using older openstack core files such as api-paste.ini, nova.conf, policy.json, etc rather than editing the existing ones - 

In general, DevOps systems should never blindly overwrite existing files; an approach like Augeas, although ambitious, is a better one; but also flawed, for different reasons.

The ini_manage module is a good start in this direction, I have small, focused utilities to (idempotently) edit config files directly rather than blindly overwrite them.

The templating mechanism is also both crude and overkill, for reasons relating to the above - what you really want is a programming approach  - This is why Puppet came up with the philosophy of a DSL, but Puppet is both too verbose and not powerful enough.

My idea here for Salt, is a coffeescript/JSON approach..

But I digress.  This would be better as a blog post...
